[theme]
primaryColor = "#e91e63"
backgroundColor = "#fce4ec"
secondaryBackgroundColor = "#ffffff"
textColor = "#880e4f"
font = "sans serif"
base = "light"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true
